//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimLibraryServiceTests.BimLibraryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    [System.SerializableAttribute()]
    public partial class Product : BimLibraryServiceTests.BimLibraryService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdditionalShippingChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowAddingOnlyExistingAttributeCombinationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowBackInStockSubscriptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCustomerReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllowedQuantitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApprovedRatingSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApprovedTotalReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutomaticallyAddRequiredProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AvailableEndDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableForPreOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AvailableStartDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.BackorderMode BackorderModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BackorderModeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CallForPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CustomerEntersPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliveryDateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisableBuyButtonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisableWishlistButtonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisplayStockAvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisplayStockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.DownloadActivationType DownloadActivationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownloadActivationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DownloadExpirationDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownloadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.GiftCardType GiftCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiftCardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GtinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDiscountsAppliedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSampleDownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasTierPricesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasUserAgreementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFreeShippingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGiftCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecurringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsShipEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTaxExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTelecommunicationsOrBroadcastingOrElectronicServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LimitedToStoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.LowStockActivity LowStockActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LowStockActivityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.ManageInventoryMethod ManageInventoryMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManageInventoryMethodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerPartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberOfDownloadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaximumCustomerEnteredPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaKeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinStockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MinimumCustomerEnteredPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotApprovedRatingSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotApprovedTotalReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotifyAdminForQuantityBelowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderMaximumQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderMinimumQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentGroupedProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PreOrderAvailabilityStartDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.ProductType ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecurringCycleLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.RecurringProductCyclePeriod RecurringCyclePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecurringCyclePeriodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecurringTotalCyclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalPriceLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BimLibraryServiceTests.BimLibraryService.RentalPricePeriod RentalPricePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalPricePeriodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequireOtherProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequiredProductIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SampleDownloadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShipSeparatelyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowOnHomePageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SpecialPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SpecialPriceEndDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SpecialPriceStartDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SubjectToAclField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaxCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UnlimitedDownloadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseMultipleWarehousesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgreementTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleIndividuallyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarehouseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdditionalShippingCharge {
            get {
                return this.AdditionalShippingChargeField;
            }
            set {
                if ((this.AdditionalShippingChargeField.Equals(value) != true)) {
                    this.AdditionalShippingChargeField = value;
                    this.RaisePropertyChanged("AdditionalShippingCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminComment {
            get {
                return this.AdminCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminCommentField, value) != true)) {
                    this.AdminCommentField = value;
                    this.RaisePropertyChanged("AdminComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowAddingOnlyExistingAttributeCombinations {
            get {
                return this.AllowAddingOnlyExistingAttributeCombinationsField;
            }
            set {
                if ((this.AllowAddingOnlyExistingAttributeCombinationsField.Equals(value) != true)) {
                    this.AllowAddingOnlyExistingAttributeCombinationsField = value;
                    this.RaisePropertyChanged("AllowAddingOnlyExistingAttributeCombinations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowBackInStockSubscriptions {
            get {
                return this.AllowBackInStockSubscriptionsField;
            }
            set {
                if ((this.AllowBackInStockSubscriptionsField.Equals(value) != true)) {
                    this.AllowBackInStockSubscriptionsField = value;
                    this.RaisePropertyChanged("AllowBackInStockSubscriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCustomerReviews {
            get {
                return this.AllowCustomerReviewsField;
            }
            set {
                if ((this.AllowCustomerReviewsField.Equals(value) != true)) {
                    this.AllowCustomerReviewsField = value;
                    this.RaisePropertyChanged("AllowCustomerReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllowedQuantities {
            get {
                return this.AllowedQuantitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedQuantitiesField, value) != true)) {
                    this.AllowedQuantitiesField = value;
                    this.RaisePropertyChanged("AllowedQuantities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovedRatingSum {
            get {
                return this.ApprovedRatingSumField;
            }
            set {
                if ((this.ApprovedRatingSumField.Equals(value) != true)) {
                    this.ApprovedRatingSumField = value;
                    this.RaisePropertyChanged("ApprovedRatingSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovedTotalReviews {
            get {
                return this.ApprovedTotalReviewsField;
            }
            set {
                if ((this.ApprovedTotalReviewsField.Equals(value) != true)) {
                    this.ApprovedTotalReviewsField = value;
                    this.RaisePropertyChanged("ApprovedTotalReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutomaticallyAddRequiredProducts {
            get {
                return this.AutomaticallyAddRequiredProductsField;
            }
            set {
                if ((this.AutomaticallyAddRequiredProductsField.Equals(value) != true)) {
                    this.AutomaticallyAddRequiredProductsField = value;
                    this.RaisePropertyChanged("AutomaticallyAddRequiredProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AvailableEndDateTimeUtc {
            get {
                return this.AvailableEndDateTimeUtcField;
            }
            set {
                if ((this.AvailableEndDateTimeUtcField.Equals(value) != true)) {
                    this.AvailableEndDateTimeUtcField = value;
                    this.RaisePropertyChanged("AvailableEndDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AvailableForPreOrder {
            get {
                return this.AvailableForPreOrderField;
            }
            set {
                if ((this.AvailableForPreOrderField.Equals(value) != true)) {
                    this.AvailableForPreOrderField = value;
                    this.RaisePropertyChanged("AvailableForPreOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AvailableStartDateTimeUtc {
            get {
                return this.AvailableStartDateTimeUtcField;
            }
            set {
                if ((this.AvailableStartDateTimeUtcField.Equals(value) != true)) {
                    this.AvailableStartDateTimeUtcField = value;
                    this.RaisePropertyChanged("AvailableStartDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.BackorderMode BackorderMode {
            get {
                return this.BackorderModeField;
            }
            set {
                if ((this.BackorderModeField.Equals(value) != true)) {
                    this.BackorderModeField = value;
                    this.RaisePropertyChanged("BackorderMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BackorderModeId {
            get {
                return this.BackorderModeIdField;
            }
            set {
                if ((this.BackorderModeIdField.Equals(value) != true)) {
                    this.BackorderModeIdField = value;
                    this.RaisePropertyChanged("BackorderModeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallForPrice {
            get {
                return this.CallForPriceField;
            }
            set {
                if ((this.CallForPriceField.Equals(value) != true)) {
                    this.CallForPriceField = value;
                    this.RaisePropertyChanged("CallForPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CustomerEntersPrice {
            get {
                return this.CustomerEntersPriceField;
            }
            set {
                if ((this.CustomerEntersPriceField.Equals(value) != true)) {
                    this.CustomerEntersPriceField = value;
                    this.RaisePropertyChanged("CustomerEntersPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveryDateId {
            get {
                return this.DeliveryDateIdField;
            }
            set {
                if ((this.DeliveryDateIdField.Equals(value) != true)) {
                    this.DeliveryDateIdField = value;
                    this.RaisePropertyChanged("DeliveryDateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DisableBuyButton {
            get {
                return this.DisableBuyButtonField;
            }
            set {
                if ((this.DisableBuyButtonField.Equals(value) != true)) {
                    this.DisableBuyButtonField = value;
                    this.RaisePropertyChanged("DisableBuyButton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DisableWishlistButton {
            get {
                return this.DisableWishlistButtonField;
            }
            set {
                if ((this.DisableWishlistButtonField.Equals(value) != true)) {
                    this.DisableWishlistButtonField = value;
                    this.RaisePropertyChanged("DisableWishlistButton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DisplayStockAvailability {
            get {
                return this.DisplayStockAvailabilityField;
            }
            set {
                if ((this.DisplayStockAvailabilityField.Equals(value) != true)) {
                    this.DisplayStockAvailabilityField = value;
                    this.RaisePropertyChanged("DisplayStockAvailability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DisplayStockQuantity {
            get {
                return this.DisplayStockQuantityField;
            }
            set {
                if ((this.DisplayStockQuantityField.Equals(value) != true)) {
                    this.DisplayStockQuantityField = value;
                    this.RaisePropertyChanged("DisplayStockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.DownloadActivationType DownloadActivationType {
            get {
                return this.DownloadActivationTypeField;
            }
            set {
                if ((this.DownloadActivationTypeField.Equals(value) != true)) {
                    this.DownloadActivationTypeField = value;
                    this.RaisePropertyChanged("DownloadActivationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DownloadActivationTypeId {
            get {
                return this.DownloadActivationTypeIdField;
            }
            set {
                if ((this.DownloadActivationTypeIdField.Equals(value) != true)) {
                    this.DownloadActivationTypeIdField = value;
                    this.RaisePropertyChanged("DownloadActivationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DownloadExpirationDays {
            get {
                return this.DownloadExpirationDaysField;
            }
            set {
                if ((this.DownloadExpirationDaysField.Equals(value) != true)) {
                    this.DownloadExpirationDaysField = value;
                    this.RaisePropertyChanged("DownloadExpirationDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DownloadId {
            get {
                return this.DownloadIdField;
            }
            set {
                if ((this.DownloadIdField.Equals(value) != true)) {
                    this.DownloadIdField = value;
                    this.RaisePropertyChanged("DownloadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullDescription {
            get {
                return this.FullDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FullDescriptionField, value) != true)) {
                    this.FullDescriptionField = value;
                    this.RaisePropertyChanged("FullDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.GiftCardType GiftCardType {
            get {
                return this.GiftCardTypeField;
            }
            set {
                if ((this.GiftCardTypeField.Equals(value) != true)) {
                    this.GiftCardTypeField = value;
                    this.RaisePropertyChanged("GiftCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiftCardTypeId {
            get {
                return this.GiftCardTypeIdField;
            }
            set {
                if ((this.GiftCardTypeIdField.Equals(value) != true)) {
                    this.GiftCardTypeIdField = value;
                    this.RaisePropertyChanged("GiftCardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gtin {
            get {
                return this.GtinField;
            }
            set {
                if ((object.ReferenceEquals(this.GtinField, value) != true)) {
                    this.GtinField = value;
                    this.RaisePropertyChanged("Gtin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDiscountsApplied {
            get {
                return this.HasDiscountsAppliedField;
            }
            set {
                if ((this.HasDiscountsAppliedField.Equals(value) != true)) {
                    this.HasDiscountsAppliedField = value;
                    this.RaisePropertyChanged("HasDiscountsApplied");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSampleDownload {
            get {
                return this.HasSampleDownloadField;
            }
            set {
                if ((this.HasSampleDownloadField.Equals(value) != true)) {
                    this.HasSampleDownloadField = value;
                    this.RaisePropertyChanged("HasSampleDownload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasTierPrices {
            get {
                return this.HasTierPricesField;
            }
            set {
                if ((this.HasTierPricesField.Equals(value) != true)) {
                    this.HasTierPricesField = value;
                    this.RaisePropertyChanged("HasTierPrices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasUserAgreement {
            get {
                return this.HasUserAgreementField;
            }
            set {
                if ((this.HasUserAgreementField.Equals(value) != true)) {
                    this.HasUserAgreementField = value;
                    this.RaisePropertyChanged("HasUserAgreement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDownload {
            get {
                return this.IsDownloadField;
            }
            set {
                if ((this.IsDownloadField.Equals(value) != true)) {
                    this.IsDownloadField = value;
                    this.RaisePropertyChanged("IsDownload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFreeShipping {
            get {
                return this.IsFreeShippingField;
            }
            set {
                if ((this.IsFreeShippingField.Equals(value) != true)) {
                    this.IsFreeShippingField = value;
                    this.RaisePropertyChanged("IsFreeShipping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGiftCard {
            get {
                return this.IsGiftCardField;
            }
            set {
                if ((this.IsGiftCardField.Equals(value) != true)) {
                    this.IsGiftCardField = value;
                    this.RaisePropertyChanged("IsGiftCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecurring {
            get {
                return this.IsRecurringField;
            }
            set {
                if ((this.IsRecurringField.Equals(value) != true)) {
                    this.IsRecurringField = value;
                    this.RaisePropertyChanged("IsRecurring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRental {
            get {
                return this.IsRentalField;
            }
            set {
                if ((this.IsRentalField.Equals(value) != true)) {
                    this.IsRentalField = value;
                    this.RaisePropertyChanged("IsRental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsShipEnabled {
            get {
                return this.IsShipEnabledField;
            }
            set {
                if ((this.IsShipEnabledField.Equals(value) != true)) {
                    this.IsShipEnabledField = value;
                    this.RaisePropertyChanged("IsShipEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTaxExempt {
            get {
                return this.IsTaxExemptField;
            }
            set {
                if ((this.IsTaxExemptField.Equals(value) != true)) {
                    this.IsTaxExemptField = value;
                    this.RaisePropertyChanged("IsTaxExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTelecommunicationsOrBroadcastingOrElectronicServices {
            get {
                return this.IsTelecommunicationsOrBroadcastingOrElectronicServicesField;
            }
            set {
                if ((this.IsTelecommunicationsOrBroadcastingOrElectronicServicesField.Equals(value) != true)) {
                    this.IsTelecommunicationsOrBroadcastingOrElectronicServicesField = value;
                    this.RaisePropertyChanged("IsTelecommunicationsOrBroadcastingOrElectronicServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LimitedToStores {
            get {
                return this.LimitedToStoresField;
            }
            set {
                if ((this.LimitedToStoresField.Equals(value) != true)) {
                    this.LimitedToStoresField = value;
                    this.RaisePropertyChanged("LimitedToStores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.LowStockActivity LowStockActivity {
            get {
                return this.LowStockActivityField;
            }
            set {
                if ((this.LowStockActivityField.Equals(value) != true)) {
                    this.LowStockActivityField = value;
                    this.RaisePropertyChanged("LowStockActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LowStockActivityId {
            get {
                return this.LowStockActivityIdField;
            }
            set {
                if ((this.LowStockActivityIdField.Equals(value) != true)) {
                    this.LowStockActivityIdField = value;
                    this.RaisePropertyChanged("LowStockActivityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.ManageInventoryMethod ManageInventoryMethod {
            get {
                return this.ManageInventoryMethodField;
            }
            set {
                if ((this.ManageInventoryMethodField.Equals(value) != true)) {
                    this.ManageInventoryMethodField = value;
                    this.RaisePropertyChanged("ManageInventoryMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManageInventoryMethodId {
            get {
                return this.ManageInventoryMethodIdField;
            }
            set {
                if ((this.ManageInventoryMethodIdField.Equals(value) != true)) {
                    this.ManageInventoryMethodIdField = value;
                    this.RaisePropertyChanged("ManageInventoryMethodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerPartNumber {
            get {
                return this.ManufacturerPartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerPartNumberField, value) != true)) {
                    this.ManufacturerPartNumberField = value;
                    this.RaisePropertyChanged("ManufacturerPartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberOfDownloads {
            get {
                return this.MaxNumberOfDownloadsField;
            }
            set {
                if ((this.MaxNumberOfDownloadsField.Equals(value) != true)) {
                    this.MaxNumberOfDownloadsField = value;
                    this.RaisePropertyChanged("MaxNumberOfDownloads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaximumCustomerEnteredPrice {
            get {
                return this.MaximumCustomerEnteredPriceField;
            }
            set {
                if ((this.MaximumCustomerEnteredPriceField.Equals(value) != true)) {
                    this.MaximumCustomerEnteredPriceField = value;
                    this.RaisePropertyChanged("MaximumCustomerEnteredPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription {
            get {
                return this.MetaDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDescriptionField, value) != true)) {
                    this.MetaDescriptionField = value;
                    this.RaisePropertyChanged("MetaDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaKeywords {
            get {
                return this.MetaKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaKeywordsField, value) != true)) {
                    this.MetaKeywordsField = value;
                    this.RaisePropertyChanged("MetaKeywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaTitleField, value) != true)) {
                    this.MetaTitleField = value;
                    this.RaisePropertyChanged("MetaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinStockQuantity {
            get {
                return this.MinStockQuantityField;
            }
            set {
                if ((this.MinStockQuantityField.Equals(value) != true)) {
                    this.MinStockQuantityField = value;
                    this.RaisePropertyChanged("MinStockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinimumCustomerEnteredPrice {
            get {
                return this.MinimumCustomerEnteredPriceField;
            }
            set {
                if ((this.MinimumCustomerEnteredPriceField.Equals(value) != true)) {
                    this.MinimumCustomerEnteredPriceField = value;
                    this.RaisePropertyChanged("MinimumCustomerEnteredPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotApprovedRatingSum {
            get {
                return this.NotApprovedRatingSumField;
            }
            set {
                if ((this.NotApprovedRatingSumField.Equals(value) != true)) {
                    this.NotApprovedRatingSumField = value;
                    this.RaisePropertyChanged("NotApprovedRatingSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotApprovedTotalReviews {
            get {
                return this.NotApprovedTotalReviewsField;
            }
            set {
                if ((this.NotApprovedTotalReviewsField.Equals(value) != true)) {
                    this.NotApprovedTotalReviewsField = value;
                    this.RaisePropertyChanged("NotApprovedTotalReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotifyAdminForQuantityBelow {
            get {
                return this.NotifyAdminForQuantityBelowField;
            }
            set {
                if ((this.NotifyAdminForQuantityBelowField.Equals(value) != true)) {
                    this.NotifyAdminForQuantityBelowField = value;
                    this.RaisePropertyChanged("NotifyAdminForQuantityBelow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldPrice {
            get {
                return this.OldPriceField;
            }
            set {
                if ((this.OldPriceField.Equals(value) != true)) {
                    this.OldPriceField = value;
                    this.RaisePropertyChanged("OldPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderMaximumQuantity {
            get {
                return this.OrderMaximumQuantityField;
            }
            set {
                if ((this.OrderMaximumQuantityField.Equals(value) != true)) {
                    this.OrderMaximumQuantityField = value;
                    this.RaisePropertyChanged("OrderMaximumQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderMinimumQuantity {
            get {
                return this.OrderMinimumQuantityField;
            }
            set {
                if ((this.OrderMinimumQuantityField.Equals(value) != true)) {
                    this.OrderMinimumQuantityField = value;
                    this.RaisePropertyChanged("OrderMinimumQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentGroupedProductId {
            get {
                return this.ParentGroupedProductIdField;
            }
            set {
                if ((this.ParentGroupedProductIdField.Equals(value) != true)) {
                    this.ParentGroupedProductIdField = value;
                    this.RaisePropertyChanged("ParentGroupedProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PreOrderAvailabilityStartDateTimeUtc {
            get {
                return this.PreOrderAvailabilityStartDateTimeUtcField;
            }
            set {
                if ((this.PreOrderAvailabilityStartDateTimeUtcField.Equals(value) != true)) {
                    this.PreOrderAvailabilityStartDateTimeUtcField = value;
                    this.RaisePropertyChanged("PreOrderAvailabilityStartDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductCost {
            get {
                return this.ProductCostField;
            }
            set {
                if ((this.ProductCostField.Equals(value) != true)) {
                    this.ProductCostField = value;
                    this.RaisePropertyChanged("ProductCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTemplateId {
            get {
                return this.ProductTemplateIdField;
            }
            set {
                if ((this.ProductTemplateIdField.Equals(value) != true)) {
                    this.ProductTemplateIdField = value;
                    this.RaisePropertyChanged("ProductTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.ProductType ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((this.ProductTypeField.Equals(value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeId {
            get {
                return this.ProductTypeIdField;
            }
            set {
                if ((this.ProductTypeIdField.Equals(value) != true)) {
                    this.ProductTypeIdField = value;
                    this.RaisePropertyChanged("ProductTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published {
            get {
                return this.PublishedField;
            }
            set {
                if ((this.PublishedField.Equals(value) != true)) {
                    this.PublishedField = value;
                    this.RaisePropertyChanged("Published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecurringCycleLength {
            get {
                return this.RecurringCycleLengthField;
            }
            set {
                if ((this.RecurringCycleLengthField.Equals(value) != true)) {
                    this.RecurringCycleLengthField = value;
                    this.RaisePropertyChanged("RecurringCycleLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.RecurringProductCyclePeriod RecurringCyclePeriod {
            get {
                return this.RecurringCyclePeriodField;
            }
            set {
                if ((this.RecurringCyclePeriodField.Equals(value) != true)) {
                    this.RecurringCyclePeriodField = value;
                    this.RaisePropertyChanged("RecurringCyclePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecurringCyclePeriodId {
            get {
                return this.RecurringCyclePeriodIdField;
            }
            set {
                if ((this.RecurringCyclePeriodIdField.Equals(value) != true)) {
                    this.RecurringCyclePeriodIdField = value;
                    this.RaisePropertyChanged("RecurringCyclePeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecurringTotalCycles {
            get {
                return this.RecurringTotalCyclesField;
            }
            set {
                if ((this.RecurringTotalCyclesField.Equals(value) != true)) {
                    this.RecurringTotalCyclesField = value;
                    this.RaisePropertyChanged("RecurringTotalCycles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalPriceLength {
            get {
                return this.RentalPriceLengthField;
            }
            set {
                if ((this.RentalPriceLengthField.Equals(value) != true)) {
                    this.RentalPriceLengthField = value;
                    this.RaisePropertyChanged("RentalPriceLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BimLibraryServiceTests.BimLibraryService.RentalPricePeriod RentalPricePeriod {
            get {
                return this.RentalPricePeriodField;
            }
            set {
                if ((this.RentalPricePeriodField.Equals(value) != true)) {
                    this.RentalPricePeriodField = value;
                    this.RaisePropertyChanged("RentalPricePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalPricePeriodId {
            get {
                return this.RentalPricePeriodIdField;
            }
            set {
                if ((this.RentalPricePeriodIdField.Equals(value) != true)) {
                    this.RentalPricePeriodIdField = value;
                    this.RaisePropertyChanged("RentalPricePeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequireOtherProducts {
            get {
                return this.RequireOtherProductsField;
            }
            set {
                if ((this.RequireOtherProductsField.Equals(value) != true)) {
                    this.RequireOtherProductsField = value;
                    this.RaisePropertyChanged("RequireOtherProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequiredProductIds {
            get {
                return this.RequiredProductIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredProductIdsField, value) != true)) {
                    this.RequiredProductIdsField = value;
                    this.RaisePropertyChanged("RequiredProductIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SampleDownloadId {
            get {
                return this.SampleDownloadIdField;
            }
            set {
                if ((this.SampleDownloadIdField.Equals(value) != true)) {
                    this.SampleDownloadIdField = value;
                    this.RaisePropertyChanged("SampleDownloadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShipSeparately {
            get {
                return this.ShipSeparatelyField;
            }
            set {
                if ((this.ShipSeparatelyField.Equals(value) != true)) {
                    this.ShipSeparatelyField = value;
                    this.RaisePropertyChanged("ShipSeparately");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowOnHomePage {
            get {
                return this.ShowOnHomePageField;
            }
            set {
                if ((this.ShowOnHomePageField.Equals(value) != true)) {
                    this.ShowOnHomePageField = value;
                    this.RaisePropertyChanged("ShowOnHomePage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SpecialPrice {
            get {
                return this.SpecialPriceField;
            }
            set {
                if ((this.SpecialPriceField.Equals(value) != true)) {
                    this.SpecialPriceField = value;
                    this.RaisePropertyChanged("SpecialPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SpecialPriceEndDateTimeUtc {
            get {
                return this.SpecialPriceEndDateTimeUtcField;
            }
            set {
                if ((this.SpecialPriceEndDateTimeUtcField.Equals(value) != true)) {
                    this.SpecialPriceEndDateTimeUtcField = value;
                    this.RaisePropertyChanged("SpecialPriceEndDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SpecialPriceStartDateTimeUtc {
            get {
                return this.SpecialPriceStartDateTimeUtcField;
            }
            set {
                if ((this.SpecialPriceStartDateTimeUtcField.Equals(value) != true)) {
                    this.SpecialPriceStartDateTimeUtcField = value;
                    this.RaisePropertyChanged("SpecialPriceStartDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SubjectToAcl {
            get {
                return this.SubjectToAclField;
            }
            set {
                if ((this.SubjectToAclField.Equals(value) != true)) {
                    this.SubjectToAclField = value;
                    this.RaisePropertyChanged("SubjectToAcl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxCategoryId {
            get {
                return this.TaxCategoryIdField;
            }
            set {
                if ((this.TaxCategoryIdField.Equals(value) != true)) {
                    this.TaxCategoryIdField = value;
                    this.RaisePropertyChanged("TaxCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UnlimitedDownloads {
            get {
                return this.UnlimitedDownloadsField;
            }
            set {
                if ((this.UnlimitedDownloadsField.Equals(value) != true)) {
                    this.UnlimitedDownloadsField = value;
                    this.RaisePropertyChanged("UnlimitedDownloads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseMultipleWarehouses {
            get {
                return this.UseMultipleWarehousesField;
            }
            set {
                if ((this.UseMultipleWarehousesField.Equals(value) != true)) {
                    this.UseMultipleWarehousesField = value;
                    this.RaisePropertyChanged("UseMultipleWarehouses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgreementText {
            get {
                return this.UserAgreementTextField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgreementTextField, value) != true)) {
                    this.UserAgreementTextField = value;
                    this.RaisePropertyChanged("UserAgreementText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorId {
            get {
                return this.VendorIdField;
            }
            set {
                if ((this.VendorIdField.Equals(value) != true)) {
                    this.VendorIdField = value;
                    this.RaisePropertyChanged("VendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisibleIndividually {
            get {
                return this.VisibleIndividuallyField;
            }
            set {
                if ((this.VisibleIndividuallyField.Equals(value) != true)) {
                    this.VisibleIndividuallyField = value;
                    this.RaisePropertyChanged("VisibleIndividually");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarehouseId {
            get {
                return this.WarehouseIdField;
            }
            set {
                if ((this.WarehouseIdField.Equals(value) != true)) {
                    this.WarehouseIdField = value;
                    this.RaisePropertyChanged("WarehouseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BimLibraryServiceTests.BimLibraryService.Product))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackorderMode", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum BackorderMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoBackorders = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllowQtyBelow0 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllowQtyBelow0AndNotifyCustomer = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadActivationType", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum DownloadActivationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WhenOrderIsPaid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manually = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GiftCardType", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum GiftCardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Virtual = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Physical = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LowStockActivity", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum LowStockActivity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableBuyButton = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unpublish = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageInventoryMethod", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum ManageInventoryMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DontManageStock = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageStock = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageStockByAttributes = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum ProductType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimpleProduct = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupedProduct = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringProductCyclePeriod", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum RecurringProductCyclePeriod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Days = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weeks = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Months = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Years = 30,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalPricePeriod", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Catalog")]
    public enum RentalPricePeriod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Days = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weeks = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Months = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Years = 30,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BimLibraryService.IBIMservice")]
    public interface IBIMservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIMservice/DoWork", ReplyAction="http://tempuri.org/IBIMservice/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIMservice/DoWork", ReplyAction="http://tempuri.org/IBIMservice/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIMservice/GetProductByName", ReplyAction="http://tempuri.org/IBIMservice/GetProductByNameResponse")]
        BimLibraryServiceTests.BimLibraryService.Product[] GetProductByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBIMservice/GetProductByName", ReplyAction="http://tempuri.org/IBIMservice/GetProductByNameResponse")]
        System.Threading.Tasks.Task<BimLibraryServiceTests.BimLibraryService.Product[]> GetProductByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBIMserviceChannel : BimLibraryServiceTests.BimLibraryService.IBIMservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BIMserviceClient : System.ServiceModel.ClientBase<BimLibraryServiceTests.BimLibraryService.IBIMservice>, BimLibraryServiceTests.BimLibraryService.IBIMservice {
        
        public BIMserviceClient() {
        }
        
        public BIMserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BIMserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BIMserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BIMserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public BimLibraryServiceTests.BimLibraryService.Product[] GetProductByName(string name) {
            return base.Channel.GetProductByName(name);
        }
        
        public System.Threading.Tasks.Task<BimLibraryServiceTests.BimLibraryService.Product[]> GetProductByNameAsync(string name) {
            return base.Channel.GetProductByNameAsync(name);
        }
    }
}
