//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimLibraryAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BimLibraryAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Code&quot;,&quot;Title&quot;,&quot;Parent&quot;
        ///&quot;01&quot;,&quot;Substructure&quot;,&quot;&quot;
        ///&quot;01.01&quot;,&quot;Foundations&quot;,&quot;01&quot;
        ///&quot;01.02&quot;,&quot;Basement Excavation&quot;,&quot;01&quot;
        ///&quot;01.03&quot;,&quot;Basement Retaining Walls&quot;,&quot;01&quot;
        ///&quot;01.04&quot;,&quot;Ground Floor Construction&quot;,&quot;01&quot;
        ///&quot;02&quot;,&quot;Superstructure&quot;,&quot;&quot;
        ///&quot;02.01&quot;,&quot;Frame&quot;,&quot;02&quot;
        ///&quot;02.01.01&quot;,&quot;Steel Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.02&quot;,&quot;Space Frames/Decks&quot;,&quot;02.01&quot;
        ///&quot;02.01.03&quot;,&quot;Concrete Casings to Steel Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.04&quot;,&quot;Concrete Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.05&quot;,&quot;Timber Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.06&quot;,&quot;Specialist Frames&quot;,&quot;02.01&quot;
        ///&quot;02.02&quot;,&quot;Upper Floors&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myFM {
            get {
                return ResourceManager.GetString("myFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Code&quot;,&quot;Title&quot;,&quot;Parent&quot;
        ///&quot;01&quot;,&quot;Substructure&quot;,&quot;&quot;
        ///&quot;01.01&quot;,&quot;Foundations&quot;,&quot;01&quot;
        ///&quot;01.02&quot;,&quot;Basement Excavation&quot;,&quot;01&quot;
        ///&quot;01.03&quot;,&quot;Basement Retaining Walls&quot;,&quot;01&quot;
        ///&quot;01.04&quot;,&quot;Ground Floor Construction&quot;,&quot;01&quot;
        ///&quot;02&quot;,&quot;Superstructure&quot;,&quot;&quot;
        ///&quot;02.01&quot;,&quot;Frame&quot;,&quot;02&quot;
        ///&quot;02.01.01&quot;,&quot;Steel Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.02&quot;,&quot;Space Frames/Decks&quot;,&quot;02.01&quot;
        ///&quot;02.01.03&quot;,&quot;Concrete Casings to Steel Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.04&quot;,&quot;Concrete Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.05&quot;,&quot;Timber Frames&quot;,&quot;02.01&quot;
        ///&quot;02.01.06&quot;,&quot;Specialist Frames&quot;,&quot;02.01&quot;
        ///&quot;02.02&quot;,&quot;Upper Floors&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NRM {
            get {
                return ResourceManager.GetString("NRM", resourceCulture);
            }
        }
    }
}
